import {
  faCircle,
  faFire,
  faDroplet,
  faBolt,
  faLeaf,
  faSnowflake,
  faHandFist,
  faSkullCrossbones,
  faMountain,
  faFeather,
  faEye,
  faBug,
  faGem,
  faGhost,
  faDragon,
  faMoon,
  faGear,
  faWandMagicSparkles,
  type IconDefinition,
} from "@fortawesome/free-solid-svg-icons";
import type { PokeType } from "@/lib/types";

export const TYPE_ICONS: Record<PokeType, IconDefinition> = {
  normal: faCircle,
  fire: faFire,
  water: faDroplet,
  electric: faBolt,
  grass: faLeaf,
  ice: faSnowflake,
  fighting: faHandFist,
  poison: faSkullCrossbones,
  ground: faMountain,
  flying: faFeather,
  psychic: faEye,
  bug: faBug,
  rock: faGem,
  ghost: faGhost,
  dragon: faDragon,
  dark: faMoon,
  steel: faGear,
  fairy: faWandMagicSparkles,
};
